version: '3.9'

services:
  project-java-react-web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: project-java-react-web-dev
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    environment:
      - REACT_APP_PUBLIC_API=http://localhost:8080
    depends_on:
      project-java-react-api-dev:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - main-network

  project-java-react-api-dev:
    image: pedro0505/ps-java-react:1.0.0
    container_name: project-java-react-api-dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 8080:8080
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
